### ISSUE TITLE
Deployed location currently unreachable

### ISSUE THREAD

**Issue by mmcneill123** [StarBrand/BEST#15]
I tried accessing https://pesb2.cl/best/ linked from the published manuscript: https://academic.oup.com/bioinformatics/article-abstract/37/10/1480/5913389?redirectedFrom=fulltext

It looks like the deployed location is currently unreachable.

**Comment by StarBrand** [comment]
The server was in maintenance. It's going to be operational soon. In the meantime, non-encrypted route currently is: [http://pesb2.cl:3838](http://pesb2.cl:3838)

Once the [official route](https://pesb2.cl/best) is available, the non-encrypted one will be blocked.

Regards.

**Comment by StarBrand** [comment]
Ok, it is ready. Check the [official site](https://pesb2.cl/best). Meanwhile, I will close the issue.

In case you have any problem related, comment here and I will re-open it.

Thanks for the feedback.

I hope it is useful to you
